### ISSUE TITLE
WebDriverException: Message: unknown error: cannot connect to chrome

### ISSUE THREAD

**Issue by imSp4rky** [LtCMDstone/MS-Rewards-Farmer-Docker#2]
When trying to run the docker, I get this error.

I've had this error previously on a Windows machine and normally requires having Chrome installed already on the machine and that fixes it. Maybe it is an out-of-date Chrome version

I see the latest version of Chrome 120.0.6099.109 which was released on 2023-12-13 same as the Windows version so unsure if it's this.

I've tried with the ENV of MSR_VISIBLE set to true or false with the same results. 

- Running on TrueNAS scale,
I didn't have any resource limits set on the container so it should use everything it needs.

Logs
```2023-12-17 23:16:16.865832-07:002023-12-18 06:16:16,865 [INFO] Cleaning up tmp folder
2023-12-17 23:16:16.866838-07:00rm: refusing to remove '.' or '..' directory: skipping '/tmp/.'
2023-12-17 23:16:16.866864-07:00rm: refusing to remove '.' or '..' directory: skipping '/tmp/..'
2023-12-17 23:16:17.407521-07:002023-12-18 06:16:17,407 [INFO] Pulling latest version of bot and updating dependencies
2023-12-17 23:16:18.040931-07:00remote: Enumerating objects: 4, done.[K
2023-12-17 23:16:18.040969-07:00remote: Counting objects:  25% (1/4)[K
remote: Counting objects:  50% (2/4)[K
remote: Counting objects:  75% (3/4)[K
remote: Counting objects: 100% (4/4)[K
remote: Counting objects: 100% (4/4), done.[K
2023-12-17 23:16:18.040978-07:00remote: Compressing objects:  25% (1/4)[K
remote: Compressing objects:  50% (2/4)[K
remote: Compressing objects:  75% (3/4)[K
remote: Compressing objects: 100% (4/4)[K
remote: Compressing objects: 100% (4/4), done.[K
2023-12-17 23:16:18.041732-07:00remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0[K
2023-12-17 23:16:18.044708-07:00Unpacking objects:  25% (1/4)
Unpacking objects:  50% (2/4)
Unpacking objects:  75% (3/4)
Unpacking objects: 100% (4/4)
Unpacking objects: 100% (4/4), 3.10 KiB | 3.10 MiB/s, done.
2023-12-17 23:16:18.051143-07:00From https://github.com/klept0/MS-Rewards-Farmer
2023-12-17 23:16:18.051164-07:007bd94a9..25c907e  master     -> origin/master
2023-12-17 23:16:18.056349-07:00Updating 7bd94a9..25c907e
2023-12-17 23:16:18.057936-07:00Fast-forward
2023-12-17 23:16:18.526422-07:00Requirement already satisfied: requests in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (2.31.0)
2023-12-17 23:16:18.731550-07:00Requirement already satisfied: selenium>=4.15.2 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (4.16.0)
2023-12-17 23:16:18.804923-07:00Requirement already satisfied: ipapi in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (1.0.4)
2023-12-17 23:16:18.836469-07:00Requirement already satisfied: undetected-chromedriver in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (3.5.4)
2023-12-17 23:16:18.877689-07:00Requirement already satisfied: selenium-wire in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (5.1.0)
2023-12-17 23:16:18.941843-07:00Requirement already satisfied: pandas in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 6)) (2.1.4)
2023-12-17 23:16:19.283417-07:00Requirement already satisfied: numpy>=1.22.2 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 7)) (1.26.2)
2023-12-17 23:16:19.697395-07:00Requirement already satisfied: setuptools>=69.0.2 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 8)) (69.0.2)
2023-12-17 23:16:20.054738-07:00Requirement already satisfied: psutil in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (5.9.6)
2023-12-17 23:16:20.253516-07:00Collecting psutil (from -r requirements.txt (line 9))
2023-12-17 23:16:20.253851-07:00Obtaining dependency information for psutil from https://files.pythonhosted.org/packages/be/fa/f1f626620e3b47e6237dcc64cb8cc1472f139e99422e5b9fa5bbcf457f48/psutil-5.9.7-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
2023-12-17 23:16:20.511168-07:00Downloading psutil-5.9.7-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
2023-12-17 23:16:20.570177-07:00Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.12/site-packages (from requests->-r requirements.txt (line 1)) (3.3.2)
2023-12-17 23:16:20.572577-07:00Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/site-packages (from requests->-r requirements.txt (line 1)) (3.6)
2023-12-17 23:16:20.574793-07:00Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/site-packages (from requests->-r requirements.txt (line 1)) (2.1.0)
2023-12-17 23:16:20.576323-07:00Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/site-packages (from requests->-r requirements.txt (line 1)) (2023.11.17)
2023-12-17 23:16:20.584573-07:00Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.12/site-packages (from selenium>=4.15.2->-r requirements.txt (line 2)) (0.23.1)
2023-12-17 23:16:20.585891-07:00Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.12/site-packages (from selenium>=4.15.2->-r requirements.txt (line 2)) (0.11.1)
2023-12-17 23:16:20.601141-07:00Requirement already satisfied: websockets in /usr/local/lib/python3.12/site-packages (from undetected-chromedriver->-r requirements.txt (line 4)) (12.0)
2023-12-17 23:16:20.628479-07:00Requirement already satisfied: blinker>=1.4 in /usr/local/lib/python3.12/site-packages (from selenium-wire->-r requirements.txt (line 5)) (1.7.0)
2023-12-17 23:16:20.629689-07:00Requirement already satisfied: brotli>=1.0.9 in /usr/local/lib/python3.12/site-packages (from selenium-wire->-r requirements.txt (line 5)) (1.1.0)
2023-12-17 23:16:20.631170-07:00Requirement already satisfied: kaitaistruct>=0.7 in /usr/local/lib/python3.12/site-packages (from selenium-wire->-r requirements.txt (line 5)) (0.10)
2023-12-17 23:16:20.632696-07:00Requirement already satisfied: pyasn1>=0.3.1 in /usr/local/lib/python3.12/site-packages (from selenium-wire->-r requirements.txt (line 5)) (0.5.1)
2023-12-17 23:16:20.634177-07:00Requirement already satisfied: pyOpenSSL>=22.0.0 in /usr/local/lib/python3.12/site-packages (from selenium-wire->-r requirements.txt (line 5)) (23.3.0)
2023-12-17 23:16:20.635414-07:00Requirement already satisfied: pyparsing>=2.4.2 in /usr/local/lib/python3.12/site-packages (from selenium-wire->-r requirements.txt (line 5)) (3.1.1)
2023-12-17 23:16:20.636873-07:00Requirement already satisfied: pysocks>=1.7.1 in /usr/local/lib/python3.12/site-packages (from selenium-wire->-r requirements.txt (line 5)) (1.7.1)
2023-12-17 23:16:20.648110-07:00Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/site-packages (from selenium-wire->-r requirements.txt (line 5)) (1.2.0)
2023-12-17 23:16:20.649182-07:00Requirement already satisfied: zstandard>=0.14.1 in /usr/local/lib/python3.12/site-packages (from selenium-wire->-r requirements.txt (line 5)) (0.22.0)
2023-12-17 23:16:20.650961-07:00Requirement already satisfied: h2>=4.0 in /usr/local/lib/python3.12/site-packages (from selenium-wire->-r requirements.txt (line 5)) (4.1.0)
2023-12-17 23:16:20.652618-07:00Requirement already satisfied: hyperframe>=6.0 in /usr/local/lib/python3.12/site-packages (from selenium-wire->-r requirements.txt (line 5)) (6.0.1)
2023-12-17 23:16:20.748458-07:00Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 6)) (2.8.2)
2023-12-17 23:16:20.750406-07:00Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 6)) (2023.3.post1)
2023-12-17 23:16:20.751482-07:00Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 6)) (2023.3)
2023-12-17 23:16:20.813112-07:00Requirement already satisfied: hpack<5,>=4.0 in /usr/local/lib/python3.12/site-packages (from h2>=4.0->selenium-wire->-r requirements.txt (line 5)) (4.0.0)
2023-12-17 23:16:20.831265-07:00Requirement already satisfied: cryptography<42,>=41.0.5 in /usr/local/lib/python3.12/site-packages (from pyOpenSSL>=22.0.0->selenium-wire->-r requirements.txt (line 5)) (41.0.7)
2023-12-17 23:16:20.842009-07:00Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 6)) (1.16.0)
2023-12-17 23:16:20.857119-07:00Requirement already satisfied: attrs>=20.1.0 in /usr/local/lib/python3.12/site-packages (from trio~=0.17->selenium>=4.15.2->-r requirements.txt (line 2)) (23.1.0)
2023-12-17 23:16:20.858433-07:00Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/site-packages (from trio~=0.17->selenium>=4.15.2->-r requirements.txt (line 2)) (2.4.0)
2023-12-17 23:16:20.859809-07:00Requirement already satisfied: outcome in /usr/local/lib/python3.12/site-packages (from trio~=0.17->selenium>=4.15.2->-r requirements.txt (line 2)) (1.3.0.post0)
2023-12-17 23:16:20.860968-07:00Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/site-packages (from trio~=0.17->selenium>=4.15.2->-r requirements.txt (line 2)) (1.3.0)
2023-12-17 23:16:20.888993-07:00Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.12/site-packages (from wsproto>=0.14->selenium-wire->-r requirements.txt (line 5)) (0.14.0)
2023-12-17 23:16:20.933892-07:00Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/site-packages (from cryptography<42,>=41.0.5->pyOpenSSL>=22.0.0->selenium-wire->-r requirements.txt (line 5)) (1.16.0)
2023-12-17 23:16:20.962699-07:00Requirement already satisfied: pycparser in /usr/local/lib/python3.12/site-packages (from cffi>=1.12->cryptography<42,>=41.0.5->pyOpenSSL>=22.0.0->selenium-wire->-r requirements.txt (line 5)) (2.21)
2023-12-17 23:16:21.019358-07:00Downloading psutil-5.9.7-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (285 kB)
2023-12-17 23:16:21.161664-07:00[?25l   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m0.0/285.5 kB[0m [31m?[0m eta [36m-:--:--[0m
[2K   [91m━━━━━[0m[91m╸[0m[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m41.0/285.5 kB[0m [31m1.4 MB/s[0m eta [36m0:00:01[0m
[2K   [91m━━━━━━━━━━━━━━━━━[0m[90m╺[0m[90m━━━━━━━━━━━━━━━━━━━━━━[0m [32m122.9/285.5 kB[0m [31m1.8 MB/s[0m eta [36m0:00:01[0m
[2K   [91m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m[90m╺[0m[90m━━[0m [32m266.2/285.5 kB[0m [31m2.4 MB/s[0m eta [36m0:00:01[0m
[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m285.5/285.5 kB[0m [31m2.2 MB/s[0m eta [36m0:00:00[0m
2023-12-17 23:16:21.445486-07:00[?25hInstalling collected packages: psutil
2023-12-17 23:16:21.445723-07:00Attempting uninstall: psutil
2023-12-17 23:16:21.462070-07:00Found existing installation: psutil 5.9.6
2023-12-17 23:16:21.466969-07:00Uninstalling psutil-5.9.6:
2023-12-17 23:16:21.489169-07:00Successfully uninstalled psutil-5.9.6
2023-12-17 23:16:21.700035-07:00Successfully installed psutil-5.9.7
2023-12-17 23:16:21.781025-07:002023-12-17T23:16:21.781025967-07:00
2023-12-17 23:16:21.781055-07:00[1m[[0m[34;49mnotice[0m[1;39;49m][0m[39;49m A new release of pip is available: [0m[31;49m23.2.1[0m[39;49m -> [0m[32;49m23.3.1[0m
2023-12-17 23:16:21.781065-07:00[1m[[0m[34;49mnotice[0m[1;39;49m][0m[39;49m To update, run: [0m[32;49mpip install --upgrade pip[0m
2023-12-17 23:16:21.965867-07:002023-12-18 06:16:21,965 [INFO] Setting discord parameter
2023-12-17 23:16:21.967209-07:002023-12-18 06:16:21,966 [INFO] Setting Chrome version
2023-12-17 23:16:21.968577-07:002023-12-18 06:16:21,968 [INFO] Starting bot
2023-12-17 23:16:22.939912-07:00test 5.803
2023-12-18 06:16:22,941 [INFO] ********************<Email>********************
2023-12-18 06:16:23,516 [INFO] Using default request storage
2023-12-18 06:16:23,526 [INFO] Created proxy listening on 127.0.0.1:37323
2023-12-18 06:16:23,526 [INFO] Using undetected_chromedriver
2023-12-18 06:16:24,550 [INFO] patching driver executable /root/.local/share/undetected_chromedriver/undetected_chromedriver
2023-12-18 06:17:26,863 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:49565
from chrome not reachable
Stacktrace:
#0 0x55997e98ed33 <unknown>
#1 0x55997e64bdbb <unknown>
#2 0x55997e635d8a <unknown>
#3 0x55997e688648 <unknown>
#4 0x55997e67f3d8 <unknown>
#5 0x55997e6d0a90 <unknown>
#6 0x55997e6c50e3 <unknown>
#7 0x55997e68d044 <unknown>
#8 0x55997e68e44e <unknown>
#9 0x55997e953861 <unknown>
#10 0x55997e957785 <unknown>
#11 0x55997e941285 <unknown>
#12 0x55997e95841f <unknown>
#13 0x55997e92520f <unknown>
#14 0x55997e97c028 <unknown>
#15 0x55997e97c1f7 <unknown>
#16 0x55997e98ded4 <unknown>
#17 0x7fa48f181044 <unknown>
Traceback (most recent call last):
  File "/app/main.py", line 39, in main
    earned_points = executeBot(currentAccount, notifier, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 213, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/browser.py", line 40, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "/app/src/browser.py", line 76, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.12/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:49565
from chrome not reachable
Stacktrace:
#0 0x55997e98ed33 <unknown>
#1 0x55997e64bdbb <unknown>
#2 0x55997e635d8a <unknown>
#3 0x55997e688648 <unknown>
#4 0x55997e67f3d8 <unknown>
#5 0x55997e6d0a90 <unknown>
#6 0x55997e6c50e3 <unknown>
#7 0x55997e68d044 <unknown>
#8 0x55997e68e44e <unknown>
#9 0x55997e953861 <unknown>
#10 0x55997e957785 <unknown>
#11 0x55997e941285 <unknown>
#12 0x55997e95841f <unknown>
#13 0x55997e92520f <unknown>
#14 0x55997e97c028 <unknown>
#15 0x55997e97c1f7 <unknown>
#16 0x55997e98ded4 <unknown>
#17 0x7fa48f181044 <unknown>

2023-12-18 06:17:26,869 [INFO] [POINTS] Data saved for the next day.```

**Comment by imSp4rky** [comment]
I noticed there's a CHROMEURL variable but when trying the latest deb file for ubuntu https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb still doesn't load chrome directly.

Even tried MSR_CHROMEURL or CHROMEDURL as a variable.

![image](https://github.com/LtCMDstone/MS-Rewards-Farmer-Docker/assets/29722511/55d0e893-29f4-420f-bd7e-e35c0b0e7be7)

Checking the shell I confirmed google chrome is installed and running on the container.

![image](https://github.com/LtCMDstone/MS-Rewards-Farmer-Docker/assets/29722511/1caf5cb6-8363-4736-919b-13945702f5fe)

Any ideas on ways to test where its breaking?

**Comment by imSp4rky** [comment]
Switching to unraid loads correctly, looks like it's some weird way docker is loaded on TrueNAS, not going to bash my head at the TrueNAS issue for a while so will just mark it as closed for now, and will reopen if i ever find a fix.
